name: Run unit tests

on:
  push:
    # For testing, run on every branch 
    # branches:
    #   - main

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update libxml2
        run: sudo apt-get update && sudo apt-get install -y libxml2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Signal_Processing_Toolbox
          cache: true

      - name: Run statements
        uses: matlab-actions/run-command@v2
        with:
       command: |
          addpath("${{ github.workspace }}/k-Wave");
          cd("${{ github.workspace }}/k-Wave/testing/unit");
          test_results_json = runUnitTests();
        startup-options: -nojvm -logfile output.log

      - name: Upload unit test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_results
          path: k-Wave/testing/unit/unit_test_results.json

      - name: Print MATLAB log
        run: cat k-Wave/testing/unit/matlab.log