name: Run unit tests

on:
  push:
    # For testing, run on every branch 
    # branches:
    #   - main

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update libxml2
        run: sudo apt-get update && sudo apt-get install -y libxml2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Signal_Processing_Toolbox
          cache: true

      - name: Run unit tests
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("${{ github.workspace }}/k-Wave");
            cd("${{ github.workspace }}/k-Wave/testing/unit");
            test_struct = runUnitTests();
            save('test_struct.mat', 'test_struct');
          startup-options: -nojvm -logfile output.log

      - name: Test results
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("${{ github.workspace }}/k-Wave");
            cd("${{ github.workspace }}/k-Wave/testing/unit");
            runUnitTests_show_results(test_struct);
          startup-options: -nojvm 

      - name: Create json artifact
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("${{ github.workspace }}/k-Wave");
            cd("${{ github.workspace }}/k-Wave/testing/unit");
            runUnitTests_actions(test_struct);
          startup-options: -nojvm 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_results
          path: ${{ github.workspace }}/k-Wave/testing/unit/test_results.json
